# Generated by Django 5.0.2 on 2024-02-24 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='date_posted',
        ),
    ]
